# Generated by Django 2.2.4 on 2019-08-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20190818_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='client',
            new_name='user',
        ),
    ]
