# Generated by Django 2.2.4 on 2019-08-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20190819_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeMedic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=50)),
                ('grade_doctor', models.CharField(choices=[('b', 'bad'), ('g', 'good'), ('e', 'excelent')], max_length=1)),
            ],
        ),
    ]
