# Generated by Django 2.2.4 on 2019-08-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_grademedic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grademedic',
            name='grade_doctor',
            field=models.CharField(choices=[('b', 'Regular'), ('g', 'Bueno'), ('e', 'Excelente')], max_length=1),
        ),
    ]
