# Generated by Django 2.2.4 on 2019-08-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CitaLog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcita',
            old_name='symptons',
            new_name='pet_sym',
        ),
    ]
