# Generated by Django 2.2.4 on 2019-08-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CitaLog', '0002_auto_20190813_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcita',
            name='end_time',
        ),
    ]
