# Generated by Django 2.2.4 on 2019-08-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CitaLog', '0003_remove_eventcita_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcita',
            old_name='doctor',
            new_name='doctor_name',
        ),
    ]
