# Generated by Django 2.2.4 on 2019-10-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitaLog', '0004_auto_20190815_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utensilio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
