# Generated by Django 2.2.4 on 2019-10-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitaLog', '0005_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
