# Generated by Django 2.2.4 on 2019-08-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet_care', '0002_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
