# Generated by Django 2.2.4 on 2019-08-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet_care', '0008_auto_20190811_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Problema',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Fecha_y_Hora_Cita',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Mascota',
            new_name='titulo',
        ),
    ]
