# Generated by Django 2.2.4 on 2019-08-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet_care', '0009_auto_20190811_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='titulo',
            new_name='title',
        ),
    ]
