# Generated by Django 2.2.4 on 2019-08-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet_care', '0010_auto_20190811_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
    ]
