# Generated by Django 2.2.4 on 2019-08-13 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet_care', '0011_remove_event_end_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pet_appointment',
        ),
    ]
