# Generated by Django 2.2.4 on 2019-08-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet_care', '0012_delete_pet_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=500)),
                ('telephone', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('birth_bate', models.DateField()),
                ('collected_number', models.IntegerField()),
            ],
        ),
    ]
