# Generated by Django 2.2.4 on 2019-08-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet_care', '0016_auto_20190813_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='password',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
