# Generated by Django 2.2.4 on 2019-08-15 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet_care', '0017_veterinarian_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veterinarian',
            old_name='birth_bate',
            new_name='birth_date',
        ),
    ]
