# Generated by Django 2.2.4 on 2019-08-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet_care', '0018_auto_20190814_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeMedic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=50)),
                ('grade_doctor', models.CharField(choices=[('b', 'bad'), ('g', 'good'), ('e', 'excelent')], max_length=1)),
            ],
        ),
    ]
