# Generated by Django 2.2.4 on 2019-08-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet_care', '0019_grademedic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeMedic',
        ),
    ]
