# Generated by Django 2.2.6 on 2019-10-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet_care', '0021_administrador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrador',
            new_name='Administrator',
        ),
    ]
